### ISSUE TITLE
create new rustlings post

### ISSUE THREAD

**Issue by desmodrone** [desmodrone/desmodrone#1]
testing issue

**Comment by desmodrone** [comment]
### Task List
- [x] Review current Rustlings post
- [x] Fill in the blanks of current post
- [x] Finalize and post
